language: cpp

dist: trusty

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cd MacMSRDriver && make kext library && cd ..; fi
  - g++ --version
  - make install prefix=.

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

